"""
This type stub file was generated by pyright.
"""

def explicit_crs_from_epsg(crs=..., epsg=...):  # -> CRS:
    """
    Gets full/explicit CRS from EPSG code provided.

    Parameters
    ----------
    crs : dict or string, default None
        An existing crs dict or Proj string with the 'init' key specifying an EPSG code
    epsg : string or int, default None
       The EPSG code to lookup
    """
    ...

def epsg_from_crs(crs):  # -> int | None:
    """
    Returns an epsg code from a crs dict or Proj string.

    Parameters
    ----------
    crs : dict or string, default None
        A crs dict or Proj string

    """
    ...

def get_epsg_file_contents(): ...
