"""
This type stub file was generated by pyright.
"""

@<Expression>
@<Expression>
@<Expression>
class :
    ...


@<Expression>
@<Expression>
class :
    ...


@<Expression>
class :
    ...


@<Expression>
@<Expression>
class :
    ...


@<Expression>
@<Expression>
class :
    ...


