"""
This type stub file was generated by pyright.
"""

"""Coordinate reference systems and functions

PROJ.4 is the law of this land: http://proj.osgeo.org/. But whereas PROJ.4
coordinate reference systems are described by strings of parameters such as

    +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs

here we use mappings:

    {'proj': 'longlat', 'ellps': 'WGS84', 'datum': 'WGS84', 'no_defs': True}
"""
def to_string(crs): # -> str:
    """Turn a parameter mapping into a more conventional PROJ.4 string.

    Mapping keys are tested against the ``all_proj_keys`` list. Values of
    ``True`` are omitted, leaving the key bare: {'no_defs': True} -> "+no_defs"
    and items where the value is otherwise not a str, int, or float are
    omitted.
    """
    ...

def from_string(prjs): # -> dict[Unknown, int | float | Unknown | Literal[True]]:
    """Turn a PROJ.4 string into a mapping of parameters.

    Bare parameters like "+no_defs" are given a value of ``True``. All keys
    are checked against the ``all_proj_keys`` list.
    """
    ...

def from_epsg(code): # -> dict[str, Unknown | bool]:
    """Given an integer code, returns an EPSG-like mapping.

    Note: the input code is not validated against an EPSG database.
    """
    ...

_param_data = ...
_lines = ...
all_proj_keys = ...
