"""
This type stub file was generated by pyright.
"""

import shapely.speedups
from .base import CAP_STYLE, JOIN_STYLE
from .geo import asShape, box, mapping, shape
from .point import Point, asPoint
from .linestring import LineString, asLineString
from .polygon import LinearRing, Polygon, asLinearRing, asPolygon
from .multipoint import MultiPoint, asMultiPoint
from .multilinestring import MultiLineString, asMultiLineString
from .multipolygon import MultiPolygon, asMultiPolygon
from .collection import GeometryCollection

"""Geometry classes and factories
"""
