"""
This type stub file was generated by pyright.
"""

from .commons import BoundingBox, Coords, Tile
from .defaults import tms
from .models import TileMatrixSet

"""
morecantile is an adpatation of mapbox/mercantile to work with custom projection.

Refs:
    - mapproxy: https://github.com/mapproxy/mapproxy
    - mercantile: https://github.com/mapbox/mercantile
    - tiletanic: https://github.com/DigitalGlobe/tiletanic

"""
__version__ = ...
