"""
This type stub file was generated by pyright.
"""

import attr
from typing import Dict, List, Sequence, Union
from .models import TileMatrixSet

"""Default Morecantile TMS."""
morecantile_tms_dir = ...
tms_paths = ...
user_tms_dir = ...
if user_tms_dir:
    ...
default_tms: Dict[str, TileMatrixSet] = ...
@attr.s(frozen=True)
class TileMatrixSets:
    """Default TileMatrixSets holder."""
    tms: Dict = ...
    def get(self, identifier: str) -> TileMatrixSet:
        """Fetch a TMS."""
        ...
    
    def list(self) -> List[str]:
        """List registered TMS."""
        ...
    
    def register(self, custom_tms: Union[TileMatrixSet, Sequence[TileMatrixSet]], overwrite: bool = ...) -> TileMatrixSets:
        """Register TileMatrixSet(s)."""
        ...
    


tms = ...
