"""
This type stub file was generated by pyright.
"""

_VALID_URLS = ...
def read_file(*args, **kwargs): # -> DataFrame:
    ...

def to_file(*args, **kwargs): # -> None:
    ...

def infer_schema(df): # -> dict[str, Unknown | List[Unknown] | str | OrderedDict[Unknown, str]]:
    ...

