"""
This type stub file was generated by pyright.
"""

import geopandas.datasets
import geopandas as gpd
import pandas as pd
import numpy as np
from geopandas._config import options
from geopandas.geoseries import GeoSeries
from geopandas.geodataframe import GeoDataFrame
from geopandas.array import points_from_xy
from geopandas.io.file import _read_file as read_file
from geopandas.io.arrow import (
    _read_feather as read_feather,
    _read_parquet as read_parquet,
)
from geopandas.io.sql import _read_postgis as read_postgis
from geopandas.tools import clip, overlay, sjoin
from geopandas.tools._show_versions import show_versions
from ._version import get_versions

__version__ = get_versions()["version"]
