"""
This type stub file was generated by pyright.
"""

import pytest

@pytest.fixture(autouse=True)
def add_geopandas(doctest_namespace): # -> None:
    ...

def pytest_configure(config): # -> None:
    ...

def pytest_runtest_setup(item): # -> None:
    ...

