"""
This type stub file was generated by pyright.
"""

"""
Intermediaries supporting GEOS topological operations

These methods all take Shapely geometries and other Python objects and delegate
to GEOS functions via ctypes.

These methods return ctypes objects that should be recast by the caller.
"""
class Validating:
    ...


class Delegating(Validating):
    def __init__(self, name) -> None:
        ...
    


class BinaryRealProperty(Delegating):
    def __call__(self, this, other): # -> float:
        ...
    


class UnaryRealProperty(Delegating):
    def __call__(self, this): # -> float:
        ...
    


class BinaryTopologicalOp(Delegating):
    def __call__(self, this, other, *args):
        ...
    


class UnaryTopologicalOp(Delegating):
    def __call__(self, this, *args):
        ...
    


